"""Authored expanded word studies, paired with new local concept sculpture."""
import json,re,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
BRIEFS=json.loads((ROOT/'briefs.json').read_text())
DATA={}
def put(slug,tagline,caption,s3,s4,deep):DATA[slug]=dict(tagline=tagline,caption=caption,s3=s3,s4=s4,deep=deep)

put('concrescence','The many become this one, then become available again.','Distinct inherited strands enter a single leaf whose unity does not abolish their different contributions.',
'''UNITY WITHOUT A HEAP|A heap remains intelligible as items gathered together; a concrescence names a process in which those items contribute to one determinate becoming. The important change concerns how the many are felt together. Numerical collection alone would miss the achieved character of the new occasion.''',
'''WHAT THE LEAF LEAVES OUT|The sculpture preserves colored tributaries inside one contour, making integration visible. Its limitation is equally instructive: an actual occasion is not a durable manufactured object. Read the leaf as a completed event whose inheritance can enter another event, rather than as an ultimate container.''',
'''The ordinary verb grow encourages a comforting picture of accumulation: experience receives another incident as a branch receives another leaf. Whitehead's technical use asks for a more radical shift. What becomes is constituted through its relations to what has already become; it is not a fully finished subject that subsequently collects properties. The resulting unity is an achievement, not the empty box in which achievement happens.

Consider listening to a familiar melody after a bereavement. Pitch, remembered performances, bodily fatigue, and present attention contribute to the experience, but no inventory of them is yet the experience's particular felt completion. This example illuminates integration without licensing the claim that every actual occasion is a human listener. That restriction matters because process philosophy generalizes beyond conscious introspection.

Try changing one inherited contribution and asking what else changes in the whole. The exercise helps distinguish a merely additive model from a relational one. Then ask what survives for the next occasion: not the unfinished making as an ongoing private act, but its determinate result as something newly available to be taken up.''')
put('conatus','To remain is already to do.','A branching root maintains its course through constraining blocks; persistence appears as activity under resistance.',
'''ESSENCE IN ACTION|The striving is not an extra wish attached to an otherwise inert thing. In Spinoza's account it expresses the thing's actual essence. This helps explain why preservation can include growth, learning, and changing relations: persistence need not mean freezing every present feature in place.''',
'''POWER AND ITS LIMITS|Observe the root's branching adjustment to the stone. The image suggests continued activity within constraints, not a promise that effort always prevails. Human applications need the same care: explaining desire through conatus neither makes every desire wise nor turns survival into an unrestricted moral command.''',
'''Imagine a musician protecting the conditions of continued practice. Rest, cooperation, rehearsal, and refusal of an exhausting schedule can all help preserve the activity through which that life expresses its capacities. The example broadens striving beyond clenched teeth or competitive victory. It also prevents a familiar error: confusing the strongest immediate impulse with the greatest enduring power of acting.

Spinoza's account belongs to a systematic metaphysics, so translating conatus directly into a modern biological drive loses part of its scope. An organism offers a vivid case, but the term does not originate as an experimentally isolated mechanism inside a nervous system. Nor is it equivalent to conscious intention. Awareness changes how human striving is understood, not whether all striving first required a reflective decision.

A useful reading exercise compares three situations: preserving a habit, abandoning a habit to retain a larger capacity, and being overcome despite sustained effort. All three complicate the slogan never give up. Conatus names an endeavor within a field of causal relations; it does not supply immunity from those relations or a simple recipe for living well.''')
put('counterfactuality','One altered condition; a world of disciplined consequences.','Matched routes differ at one gate, isolating the changed condition from the surrounding scene.',
'''HOLDING THE BACKGROUND STILL|Counterfactual reasoning needs selective stability. To ask whether a bridge closure delayed an ambulance, keep relevant circumstances comparable before tracing consequences of reopening it. Changing every background condition at once would make the imagined improvement impossible to attribute to the particular intervention under consideration.''',
'''THE DANGER OF HINDSIGHT|Knowing the actual outcome can make an alternative seem more predictable than it was. Historical counterfactuals therefore require evidence about available choices and constraints. The paired routes invite comparison, but their symmetry is an analytical convenience: real histories may amplify a small difference through many interactions.''',
'''The sentence if the match had been struck, it would have lit is neither a report of an actual flame nor an unconstrained invention. It compresses assumptions about dryness, oxygen, friction, and the match's condition. Discovering that the match was soaked changes the judgment even though its unstruck status stays the same. Background information does real explanatory work.

Different theories formalize that work differently. A possible worlds approach compares suitably similar alternatives; a causal model represents relations and asks what follows from changing a variable. Neither brief description settles the difficult question of which similarities or causal structures are justified. The relevant standard depends partly on the inquiry: physical explanation, legal responsibility, personal regret, and strategic planning ask overlapping but distinct questions.

For practice, state an alternative outcome, identify the intervention, and list three facts you are holding constant. Then vary one of those facts. If the conclusion reverses, you have located a sensitive assumption rather than necessarily disproved the whole exercise. Disciplined imagination earns its usefulness by exposing such dependencies instead of hiding them behind the apparent fluency of a story.''')
put('defamiliarization','Recognition delayed, perception renewed.','An enlarged spoon becomes a metallic terrain before its everyday identity settles into view.',
'''DIFFICULTY WITH A PURPOSE|An unfamiliar perspective can slow recognition long enough for texture, movement, or habit to become perceptible. That delay distinguishes a productive artistic obstacle from accidental confusion. The reader's effort should reveal something about the familiar object, although the revelation need not reduce to a single message.''',
'''WHO FINDS IT STRANGE|No object is equally familiar to every audience. A technique that renews one reader's attention may feel ordinary to another or become conventional through repetition. Ask whose habits the work interrupts and what the interruption makes available; strangeness is a relation, not an intrinsic decorative property.''',
'''Take the act of unlocking a door. An ordinary account might name the key, the lock, and the entrance so efficiently that almost nothing is perceived. Another account could dwell on the small tooth pattern negotiating a hidden metal arrangement. The second delays the usual category without necessarily introducing impossible events. Its success depends on whether the detour intensifies the experience of the action.

This distinction helps separate defamiliarization from surreal imagery. A flying door may certainly estrange a scene, but an exact description of a familiar door can do so as well. Conversely, impossible images can become routine conventions within a genre. Novelty alone is a weak measure of renewed perception.

A practical exercise is to describe a household object without using its ordinary name, then restore the name at the end. Read the passage twice. The first reading tests delayed recognition; the second tests whether recognizable details remain newly vivid after the puzzle has been solved. If nothing survives except the trick, the work has created a riddle more successfully than a lasting transformation of attention.''')
put('dehiscence','An opening whose meaning depends on the living system.','Three sculptural pods separate along seams, revealing and then releasing their enclosed seeds.',
'''SAME EVENT, DIFFERENT VALUE|A botanical opening can complete a normal reproductive process, while wound separation can disrupt healing. The shared word records a structural likeness without making the events biologically equivalent. Context determines whether the opening is expected, dangerous, or merely descriptive; release is not an inherent moral good.''',
'''READING A SEAM|The seam matters because an opening follows or exposes a boundary. In a pod, specialized structures and drying processes can help make separation orderly. The sculpture abstracts those relationships, so its sequential forms should be read as a concept diagram rather than a species identification.''',
'''A word can travel between disciplines because two events share a visible pattern while performing very different roles. Dehiscence makes that travel unusually clear. The opening of a fruit may distribute seeds; the separation of a surgical closure may compromise recovery. The morphology invites comparison, but comparison does not transfer the event's value, cause, or practical response.

Even within botany, there is no single universal mechanism behind every opening structure. Different fruits, anthers, and other organs release their contents through different arrangements. A generalized pod image is therefore useful at the level of opening and containment, but should not be mistaken for a detailed biological claim about all plants.

For a reading exercise, write one sentence in which dehiscence names a physical event and another in which it works as a metaphor for disclosure. Then inspect what the metaphor imports. Does it imply a natural maturity, an injury, or a pressure that has exceeded containment? Those associations can conflict. Choosing among them deliberately makes the figurative use more exact and keeps the image of liberation from obscuring the possibility of damage.''')
put('derealization','The world recognized, its felt nearness altered.','A coherent interior recedes behind a wavering foreground plane, preserving recognition while suggesting felt distance.',
'''FEELING IS NOT A VERDICT|A person can know that the room is real while finding its familiarity emotionally inaccessible. That distinction between reality testing and felt reality is central to understanding the experience. Describing the sensation as unreal should not be automatically interpreted as endorsing a delusion about the room.''',
'''AN IMAGE CANNOT DIAGNOSE|The glasslike screen gives visual form to a possible report, not a universal symptom portrait. Experiences vary, and clinical interpretation depends on duration, distress, impairment, and context. Keep the artwork's metaphor separate from diagnostic criteria and avoid turning aesthetic estrangement into evidence of a disorder.''',
'''Ordinary language makes this experience difficult to describe because real can refer both to what exists and to how present or immediate something feels. Saying the kitchen is unreal may therefore mislead a listener who hears a claim about existence when the speaker is trying to describe a change in experience. Careful explanation preserves that ambiguity long enough to resolve it.

Derealization and depersonalization can occur together, but their emphases differ. The former concerns the experienced world; the latter concerns detachment from oneself. Neither word should become a casual synonym for being distracted, imaginative, or philosophically skeptical. Their clinical uses have more specific contexts, while transient experiences do not by themselves establish a disorder.

The illustration deliberately keeps furniture coherent. It places the interpretive burden on a relation of distance rather than on spectacular distortions or frightening figures. As a reading exercise, compare the statements I know this is my kitchen and it does not feel like my kitchen. Their coexistence is not simply a logical contradiction. It reveals that recognition, ownership, emotional familiarity, and perceptual presence can come apart in experience.''')
put('diachronicity','A form persists by becoming historically different.','Four architectural states share a ground line while their materials, heights, and uses change.',
'''SEQUENCE IS NOT DESTINY|A series of historical states can display transformation without proving improvement or a necessary destination. Later does not automatically mean better, and a present institution need not be the purpose of its predecessors. Diachronic analysis becomes stronger when it explains contingencies as well as continuities.''',
'''CHOOSING WHAT PERSISTS|To compare successive states, an analyst must decide what counts as the same language, neighborhood, or practice across change. Those decisions are substantive. The shared foundation in the artwork offers one continuity, while altered buildings ask which social relations survive, disappear, or acquire new names.''',
'''A history of a word can follow shifts in sound, spelling, meaning, and social use. These changes do not necessarily move together. A spelling may remain stable while pronunciation changes; a familiar sound may acquire a new political association. Diachronicity names the perspective that makes such temporal relations central, not a single kind of change.

A synchronic account is not thereby inferior. Understanding a particular stage may require mapping its internal contrasts before comparing it with another stage. In language, a sound's significance depends partly on its relations to other sounds at that time. A rigorous history therefore often alternates between describing configurations and explaining transformations between them.

For practice, choose a street, a family expression, or a workplace custom and identify three moments. At each moment, record both a feature that seems continuous and a relation that has altered. Then question the boundaries of the object you selected. If a neighborhood's buildings survive but its residents are displaced, continuity of architecture cannot stand in for continuity of community. Temporal comparison gains precision when it states what is being tracked.''')
put('differance','Meaning differs, and its arrival is deferred.','Offset incomplete contours become legible through their neighbors without producing a final resolving plate.',
'''THE SILENT DIFFERENCE|In standard French pronunciation, the altered spelling cannot be heard as a different vowel. The example therefore gives writing philosophical work that speech alone cannot perform. The point is not that print is always superior, but that the alleged self sufficiency of immediate spoken presence becomes questionable.''',
'''OPENNESS WITH CONSTRAINTS|If meaning depends on differences and traces, interpretation remains answerable to them. A reading that ignores a crucial opposition or context can still be criticized. Différance resists a final foundation outside signification; it does not provide a license to replace a text with any preferred fantasy.''',
'''Try defining a simple word without using another sign. A gesture, an example, and an image may help, but each still operates through relations and context. This does not mean communication never succeeds. It means the imagined escape into perfectly self present meaning cannot simply be assumed as the hidden guarantee of every successful exchange.

The temporal dimension matters as much as the relational one. Understanding unfolds through what has already been marked and what further context may disclose. A sentence's early words change significance as its later words arrive. This everyday observation is only an entry point, not an exhaustive account of Derrida's intervention.

A disciplined exercise follows one opposition in a passage: inside and outside, original and copy, or speech and writing. Ask whether the allegedly secondary term is required to articulate the primary one. The answer must arise from the passage's workings, not from mechanically reversing the hierarchy. The sculptural plates model dependence and delay; they do not depict a mysterious substance called différance sitting behind language. The word names a challenge to that very expectation of a final hidden object.''')
put('disanalogy','Where resemblance stops supporting the inference.','Similar branching structures differ in growth and jointed construction; one stressed connection exposes the comparison’s limit.',
'''RELEVANCE BEFORE DIFFERENCE|Every pair of things differs in countless ways. A disanalogy matters when a difference changes the inference being drawn from their similarity. Ask which conclusion the comparison is meant to support before listing contrasts; otherwise criticism can become a catalogue of differences that leave the argument untouched.''',
'''MODELS WITH BOUNDARIES|A model can remain useful after one disanalogy is identified. A scale bridge may illuminate shape while failing to reproduce every material stress. The sensible response is to restrict or revise its claims, not assume that imperfect resemblance makes all modeling worthless or all extrapolation safe.''',
'''Suppose a speaker argues that managing a country is like managing a household because both must allocate limited resources. The similarity may be illuminating at one level. It becomes less reliable when the argument transfers conclusions about currency issuance, taxation, or aggregate spending without examining differences in institutional power. The relevant disanalogy concerns the proposed inference, not whether governments live in kitchens.

This example reveals why criticism should reconstruct a comparison charitably before challenging it. A metaphor intended to explain budgeting priorities is making a weaker claim than a model offered to predict macroeconomic effects. The same difference can be irrelevant to the first purpose and decisive for the second.

A practical test has three steps. State the shared relation, write the conclusion being transferred, and identify a difference that changes whether the conclusion follows. Then consider whether the analogy survives in a narrower role. This method preserves the imaginative usefulness of comparison while preventing likeness from quietly becoming identity. In the sculpture, branching is the shared relation; living growth and manufactured joints represent different causal histories and capacities.''')
put('dissensus','A dispute about who can count as a participant.','Arriving chairs reshape an established meeting perimeter, making the allocation of speaking places itself visible.',
'''BEFORE THE VOTE|An ordinary disagreement assumes a recognized group deciding a recognized issue. Political dissensus in Rancière's sense can challenge those assumptions themselves. The conflict may concern whether excluded people have a voice and whether their experience belongs within the matters the community can discuss publicly.''',
'''VISIBILITY IS ORGANIZED|The seating arrangement is not neutral scenery: it assigns places, capacities, and expectations. By changing that arrangement, the sculpture makes participation perceptible as a contested practice. It does not claim that every interruption is emancipatory; the political force depends on what exclusion is exposed and contested.''',
'''Imagine residents whose housing conditions are treated as private misfortunes rather than a public matter. Petitioning for an improved policy can be one kind of disagreement. Demonstrating that their experiences constitute a common issue, and that they can speak as equals about it, alters the scene in which policy disagreement becomes possible. This distinction helps make the specialized sense of dissensus concrete.

The ordinary word still has a broader life. A committee divided over a budget can display dissensus simply because agreement is absent. Importing the full philosophical account into every such use would overread the word. Conversely, reducing Rancière's term to vigorous debate misses its concern with the organization of perception and social participation.

For an interpretive exercise, examine a meeting, a public hearing, or a fictional council. Identify who is allowed to speak, what counts as an argument, and which experiences remain outside the official agenda. Then distinguish disagreement within those rules from a challenge to the rules of visibility themselves. The extra chairs in the image do not merely increase attendance; they call the prior definition of a legitimate place into question.''')
put('dithyramb','Praise rising beyond its ordinary measure.','Interwoven rising bands and choral markers turn collective utterance into an abundant sculptural rhythm.',
'''A GENRE AND A TONE|The ancient performance form and the modern adjective do different jobs. Calling a review dithyrambic usually describes its exuberance, not its meter or ritual setting. The historical association enriches the comparison, but a contemporary burst of praise need not reproduce an ancient choral practice.''',
'''ABUNDANCE UNDER CONTROL|Extravagance can be carefully made. Repeated sounds, accumulating images, and a rising rhythm may sustain a dithyramb's force without abandoning craft. Test whether the verbal energy changes perception of its subject or merely inflates approval; enthusiasm can illuminate, overwhelm, or become comically disproportionate to its occasion.''',
'''The image of a chorus helps prevent a narrow identification of exuberance with one unusually loud individual. Choral performance organizes bodies, voices, and time. Even when later literary usage detaches dithyramb from its ancient institutional setting, the remembered possibility of collective intensity contributes to the word's resonance.

Historical caution is necessary because modern fantasies of Dionysian abandon can flatten the evidence. Ancient performance traditions were particular practices with conventions and contexts, not simply spontaneous chaos. Likewise, the relation between dithyramb and tragedy cannot be reconstructed by assuming that one surviving definition supplies the complete history of theatrical development.

For a writing exercise, praise an ordinary object in three increasingly expansive sentences. Let the first identify an actual quality, the second amplify its effects, and the third risk disproportion. Then revise the sequence so that rhythm earns the escalation. The point is not to suppress delight but to make its force legible. Reading the result aloud reveals where breath, accumulation, and emphasis help the subject appear newly radiant, and where the rhetoric begins praising its own capacity to praise.''')
put('ekphrasis','An image enters language and acquires time.','Colored verbal ribbons leave a framed relief, suggesting interpretation crossing from visual form into unfolding discourse.',
'''DESCRIPTION CHOOSES A PATH|An image may offer several features simultaneously, but a sentence must arrange their presentation. The writer therefore directs attention through sequence, emphasis, and omission. Even a careful inventory becomes an interpretation through that ordering; verbal representation does not simply duplicate the viewer's encounter with the object.''',
'''WHEN THE IMAGE ANSWERS|An ekphrastic poem may address an artwork, imagine a depicted person's voice, or question the scene's exclusions. These inventions should remain distinguishable from factual art history. The productive encounter allows language to test the image's silence without pretending that imaginative speech is documentary evidence.''',
'''Imagine two descriptions of the same portrait. One begins with the sitter's expensive fabric; another begins with the tired position of a hand. Neither has altered the paint, yet each establishes a different route through the work and a different expectation about the person represented. Ekphrasis makes that directional power part of literary form.

The encounter can also be critical. A poem might notice that a celebratory painting excludes the labor that sustained the scene. Such a reading need not reduce the artwork to a hidden message waiting to be decoded. It can expose a tension between what the image presents, what its form makes possible, and what the writer brings to the encounter.

For practice, describe a visual work in three modes: inventory, address, and imagined response. Mark which statements concern visible features and which are inferences or inventions. This distinction protects accuracy while preserving imaginative freedom. Finally, read the description without viewing the work. What duration, voice, or expectation has the prose created that the original image could not provide in precisely the same way? That difference is part of ekphrasis's achievement.''')
put('echolalia','Repeated speech can carry a present intention.','Related wave forms pass between changing response markers, showing repetition participating in communication.',
'''CONTEXT CARRIES FUNCTION|The same repeated phrase can request, affirm, rehearse, regulate, or serve another purpose in different circumstances. Its function cannot be inferred from repetition alone. Listen to timing, gesture, prior interaction, and the person's communication patterns before deciding what the utterance is doing in that particular exchange.''',
'''PATTERN WITHOUT PREJUDGMENT|Calling a repetition echolalia identifies a speech pattern rather than measuring someone's intelligence or understanding. It also does not establish a diagnosis. The sculpture keeps the repeated contour recognizable while changing its setting, emphasizing that borrowed wording can become meaningful within a new communicative situation.''',
'''Suppose a familiar phrase from a story appears during a stressful transition. An observer might hear irrelevant quotation. Someone who knows the speaker and the phrase's history may recognize an attempt to communicate a need, anticipate an event, or manage uncertainty. Understanding requires attention to the interaction rather than a rule that all repetition means the same thing.

This does not imply that every echoed utterance has an easily translated hidden message. Functions vary, and observers can overinterpret as well as dismiss. A careful account allows for uncertainty while treating the speaker as a person whose communication deserves patient consideration. Immediate and delayed repetition also introduce different temporal relations to the original speech.

As an interpretive exercise, place one repeated phrase in three situations and ask what changes. Who spoke first, how long ago, with what gesture, and toward what possible outcome? This method shifts attention from a decontextualized symptom label to an actual exchange. The distinction from palilalia remains useful: repeating another's heard speech and repeating one's own speech are different descriptive patterns, even when both involve audible recurrence.''')
put('eidolon','A likeness with the weight of an absent presence.','Incomplete overlapping human contours rise above an empty support, offering likeness without a solid inhabitant.',
'''IMAGE AND ORIGINAL|An eidolon can preserve recognizable form while unsettling the relation between image and bodily presence. Its literary force comes from that uncertainty. The reader may encounter a ghost, a memory, or an idealized figure, and the surrounding work determines how literally any apparition should be understood.''',
'''THE WORK OF ABSENCE|A remembered person can become more fixed in imagination than any living person could remain. The eidolon then exposes memory's creative power as well as its fidelity. Ask which features are preserved, which are idealized, and whose desire gives the absent figure its continuing apparent presence.''',
'''A portrait points toward someone represented, but an eidolon often makes that pointing unstable. The image seems to linger where the person cannot be reached. This can produce grief, attraction, unease, or a sense that representation has acquired a life its original never possessed. The term's flexibility is valuable precisely because it can move among phantom, likeness, and idealized image without reducing them to one phenomenon.

That literary flexibility should not become a clinical claim. A poem saying that a dead friend occupies a chair may dramatize memory without reporting a perceptual experience, much less a diagnosis. Reading figurative language carefully involves attending to genre and voice before translating the image into assertions about an author's mental state.

Try describing an absent person through three ordinary objects and no bodily features. Then notice how the description begins to generate a presence from traces. What is being recovered, and what is being composed? The sculpture's missing center gives material form to this question. It allows recognition to emerge through contours while refusing to supply the solid body that recognition seems to promise.''')
put('ekstasis','Standing beyond the place from which one stands.','Ribbons depart a bounded center and gather beyond it, giving outward relation a visible trajectory.',
'''TRANSPORT IS ONE REGISTER|Religious ecstasy, aesthetic absorption, and philosophical ekstasis should not be collapsed into a single extraordinary experience. A musical example may illuminate departure from habitual self attention. It cannot establish a theological interpretation or substitute for an argument about the temporal structure of human existence.''',
'''TIME BEYOND A POINT|In Heidegger's account, the ecstatic character of temporality concerns interrelated ways of standing beyond a punctual present. Future and having been are not simply absent boxes beside now. The artwork's outward movement is therefore a metaphor for relational extension, not a diagram of leaving one's body.''',
'''The ordinary picture of time places a tiny present between an absent past and an absent future. Heidegger's language of ecstatic temporality challenges the sufficiency of that picture for understanding existence. A promise, for example, is intelligible through an anticipated possibility and a history of commitment; its present significance is not sealed inside an isolated instant.

This example is an orientation, not a replacement for the philosophical argument. The technical sense concerns how existence is temporally structured, while religious and aesthetic uses may describe altered modes of attention or transport. Similar vocabulary can connect them without making them interchangeable. The modern association of ecstasy with intense pleasure covers only part of the semantic field.

For a reading exercise, take a sentence about waiting for someone. Identify the remembered encounter, the anticipated arrival, and the present activity. Ask whether these are merely three independent contents or whether each changes the meaning of the others. The sculpture starts within a frame but carries its strands beyond that frame. Its subject is the insufficiency of enclosure, not an empirical claim about a soul visibly escaping a body.''')
put('elenchus','A claim tested against what its speaker also accepts.','A closed path of commitments meets an opposing arrow, exposing tension within the same argumentative structure.',
'''CONTRADICTION HAS A COST|When accepted commitments conflict, something needs revision, but the inconsistency does not identify its own repair. The initial definition, an accepted example, or another premise may be abandoned. This is why elenchus can generate productive perplexity without automatically delivering a finished replacement doctrine.''',
'''QUESTIONING AS COOPERATION|The method depends on taking answers seriously enough to follow their consequences. Questions designed only to embarrass can resemble the outward pattern while undermining inquiry. Ask whether the participants are free to revise a claim and whether the exchange clarifies the disputed concept for everyone involved.''',
'''Consider a definition of honesty as always telling the truth. The questioner introduces a case in which revealing someone's hiding place to an attacker would facilitate harm. If the respondent accepts both the definition and the judgment that concealment is justified, a tension has appeared. The discussion must now clarify whether honesty, obligation, and truth telling have been related too simply.

This exercise does not by itself settle the ethical case. A respondent may challenge the example, qualify the definition, or distinguish competing duties. What matters is that the initial confidence has become answerable to other commitments. The method examines the speaker's position from within rather than importing a complete theory without discussion.

For practice, write a definition of a familiar virtue and then list three cases you are confident about. Look for a case the definition classifies in an unexpected way. Do not immediately force the example into compliance. The difficulty may reveal a genuine ambiguity in the concept. An elenchus succeeds when that difficulty becomes visible and discussable, even if the participants end with a better question rather than a final answer.''')
put('enallage','A grammatical exchange that changes the force of saying.','A round form interrupts an ordered sequence of blocks while the displaced form appears outside its expected position.',
'''EXPECTATION MAKES THE FIGURE|A substitution becomes rhetorically perceptible against an expected form. The relevant expectation may concern tense, person, number, or another grammatical feature. Describe the local pattern before declaring a departure; without that baseline, a reader may mistake ordinary variation for a deliberate expressive exchange.''',
'''VARIATION IS NOT DEFECT|A dialect's regular grammar is not a rhetorical error merely because a prestige standard differs. Likewise, traditional classifications of enallage overlap and vary. The useful analytical question concerns the expressive consequence of a specific shift, not the satisfaction of policing every sentence into one approved mold.''',
'''A narrator who moves from past tense into the present can bring an event startlingly close: the door opened becomes the door opens. The change may make a remembered scene feel immediate, shift the relation between teller and event, or establish a new narrative pattern. Calling the change enallage identifies an exchange of grammatical form within a broad rhetorical vocabulary; it does not exhaust the literary explanation.

The category has never had perfectly uniform borders. Some handbooks separate figures that others include under grammatical exchange. That variation recommends precision about the actual construction rather than reliance on the label alone. A description of what changes, where it changes, and what effect follows is more informative than a taxonomy without an example.

For practice, retell a short event three ways: first person, second person, and historical present. Compare the distribution of responsibility and distance. Then distinguish deliberate shifts within a passage from stable grammatical features of a language variety. The sculpture's substituted shape is visible because the sequence establishes an expectation, but language's expectations are social and contextual rather than universally fixed geometric slots.''')
put('energeia','A capacity present in its exercise.','A closed and an open eye distinguish retained capacity from seeing in activity.',
'''ACTIVITY AND PRODUCTION|Seeing is complete as seeing while it occurs; building is directed toward a house not yet completed. Aristotle uses distinctions of this kind to investigate actuality and process. They resist the modern habit of measuring every activity by a separate product that will eventually justify it.''',
'''BEYOND MODERN ENERGY|The resemblance to energy can mislead. Energeia is not a quantity measured in joules or a synonym for enthusiasm. Locate the term beside potentiality and the particular activity being discussed; its philosophical work depends on those contrasts, including its substantial overlap with entelecheia in Aristotle.''',
'''A person who knows a language possesses a capacity even while asleep. Speaking meaningfully exercises that capacity. This contrast offers an approachable entry into actuality without requiring that every case of being actual look like visible movement. The relevant distinction is not simply stillness versus motion, but the relation between what something can do and its being at work.

The relation between activity and an external end adds another layer. A builder's work aims at a house that can stand after the building process ends. Seeing does not need to leave behind a separate object to count as seeing. Such examples help explain why the terminology cannot be reduced to productivity, effort, or personal drive.

For an interpretive exercise, compare learning a skill, possessing the skill, and exercising it. Ask where completion belongs in each description and which kind of potentiality is being actualized. Different Aristotelian arguments may organize the contrasts differently, so the exercise is a guide to questions rather than a universal translation key. The open eye in the artwork makes one activity legible while leaving the broader metaphysical account to the accompanying explanation.''')
put('entelechy','Completeness need not be constant performance.','A fully assembled lyre at rest embodies a formed capacity without requiring that its strings be sounded.',
'''A FIRST ACTUALITY|Possessing knowledge is already an actuality relative to not knowing, although actively contemplating differs from merely possessing it. Aristotle's account of soul uses a comparable distinction. A living body's organization matters even when it is not exercising every capacity; actuality has more than one explanatory level.''',
'''NO GUARANTEED DESTINY|The word's association with fulfillment can tempt a story in which every seed or person inevitably reaches a predestined perfection. That story exceeds the concept. Material conditions, impediments, and the particular philosophical framework matter; later vitalist meanings should not be silently substituted for Aristotle's account.''',
'''An instrument assembled and tuned is different from a collection of timber, metal, and string. Its organization makes certain activities possible. Yet the instrument need not be playing at every moment to possess that organized capacity. This analogy helps distinguish first actuality from an active exercise, while remaining only an analogy for Aristotle's account of a living body.

The soul in that account should not be casually pictured as a little operator hidden inside biological machinery. The formulation concerns the actuality of a natural organized body potentially possessing life. Interpreting its full implications requires attention to Aristotle's arguments, not merely to a modern opposition between material mechanism and supernatural occupant.

Try comparing three descriptions: the materials for a lyre, the completed lyre, and a performed melody. Each brings a different relation of capacity and actuality into view. Then ask where the analogy to a living thing begins to fail, particularly because an artifact's organization and a natural organism's life are not identical cases. The exercise makes the term more precise by acknowledging that no single miniature example can settle every use of entelechy.''')
put('enthymeme','Persuasion asks the listener to supply a bridge.','An emphasized central segment makes the audience’s usually unstated support visible within an argumentative bridge.',
'''THE AUDIENCE PARTICIPATES|Compression can persuade because listeners complete a plausible connection themselves. That participation gives an enthymeme rhetorical force while making its assumptions less conspicuous. Reconstructing the missing bridge does not automatically refute the argument; it identifies what the audience must accept for the conclusion to seem warranted.''',
'''REASONS SHORT OF CERTAINTY|Practical persuasion often concerns probabilities, signs, and shared judgments. An argument can be reasonable without furnishing deductive certainty. Distinguish a hidden premise from a false one, and distinguish both from the broader Aristotelian account of rhetorical proof; the familiar omission formula is useful but incomplete.''',
'''The sentence the candidate understands ordinary workers because she once worked in a warehouse asks its audience to contribute several connections. Experience may support understanding; the past job may be relevant to the present role; other experiences may not have erased that understanding. Making these assumptions explicit changes the quality of the discussion.

Some assumptions may be plausible but defeasible. A person can have relevant experience without representing everyone's interests, and biographical similarity does not guarantee sound policy. The enthymeme's efficiency comes partly from letting a shared inference remain unobtrusive. Its weakness may appear when different audiences supply different bridges while believing they have heard the same argument.

For practice, collect a short recommendation, advertisement, or political claim. Write the implied premise in ordinary language, then state a circumstance in which it would fail. This does not require treating every compressed argument as manipulation. Conversation would become cumbersome if every inference were fully expanded. The aim is selective attention: to notice which omitted commitments carry the weight when the consequences of accepting a claim become significant.''')
# The added poster sections deepen the initial brief rather than repeat its caveats.
DATA['differance']['s3']='TRACE WITHOUT A LOST ORIGIN|To call a mark a trace is not simply to say that it records an earlier, fully present object. It bears relations to what is absent from its immediate appearance. The past and anticipated future of a word participate in what seems to be its present meaning.'
DATA['differance']['s4']='READING AN OPPOSITION|Consider calling one version of a story the original and another a copy. The original becomes identifiable through the possibility of repetition, quotation, and alteration. Reading this dependency closely complicates its apparent independence without claiming that the two versions have identical histories or authority.'
put('epanalepsis','The returning word arrives with a changed history.','Matching terminal rings enclose a varied intervening path, making recurrence visible as an altered arrival.',
'''THE RETURN REVISES THE START|In Hope was what remained after we had exhausted hope, the repeated word names both an initial resource and a diminished residue. The intervening clause changes its force. Such a sentence demonstrates why repetition can produce semantic movement even when the written form remains exactly the same.''',
'''CLOSURE OR CAPTIVITY|An enclosing repetition may sound resolved, trapped, ironic, or obsessive. Try varying the sentence between its matching ends while keeping the ends fixed. A return after discovery differs from a return after defeat; the figure supplies a structure whose emotional trajectory must be made by the passage.''',
'''The second occurrence asks the reader to remember the first, but memory is now filtered through the intervening language. This is a small temporal drama: recognition and revision arrive together. The phrase seems familiar because it has returned, yet the reader has traveled a route that its earlier appearance could not contain in exactly the same way.

A useful comparison is the refrain. A refrain may recur across larger divisions of a work, gathering associations with each return. Epanalepsis, in its familiar narrower definition, encloses a clause or sentence. Traditional rhetorical boundaries vary, but the difference in scale changes the reading experience. A brief enclosure can feel like a thought turning back on itself before it has escaped its own premise.

For practice, begin and end three sentences with the same noun. Make one consoling, one comic, and one accusatory. Read the sentences aloud, giving the final word a slightly different stress each time. The exercise reveals how punctuation, intervening syntax, and performance can alter the relation between the two occurrences. The sculptural path has unequal intermediate forms because a verbal return need not imply that nothing happened along the way.''')
put('epenthesis','A sound arrives inside the sequence.','An additional central bead joins an existing chain, while an elevated precursor marks the act of insertion.',
'''ARTICULATION HAS TIMING|Between neighboring speech gestures, a brief additional sound can emerge through their coordination. In some pronunciations of warmth, the transition from a nasal toward the following consonant can produce a stoplike interval. The example concerns articulatory timing, not the conscious decision to add a written letter.''',
'''BORROWING CHANGES THE FIT|A borrowed word may contain clusters disallowed by the receiving language's sound patterns. Inserting a vowel can adapt the sequence to those patterns. Comparing the source and borrowed pronunciations reveals how languages reshape inherited material; copying a spelling does not guarantee copying its syllable structure.''',
'''Writing can hide epenthesis because a spelling may remain unchanged while speakers regularly produce an additional sound. The reverse complication also occurs: an extra letter in a spelling does not by itself demonstrate that a new spoken segment is present. The analysis therefore needs pronunciation data and an account of the language variety involved.

Epenthesis can be discussed at different levels. A brief transitional sound may arise through articulation, while a stable inserted vowel in borrowed words may reflect a productive phonological pattern. Deciding how to analyze a particular case requires evidence about consistency, distribution, and the relationship between phonetic detail and a language's categories.

For practice, compare a borrowed word's pronunciation in its source language with its pronunciation in another language. Mark syllable boundaries and identify any added segments. Then ask whether the receiving language allows the original cluster in other words. This question connects the local example to a broader pattern rather than treating difference as carelessness. The central bead in the artwork is intentionally a different color: insertion adds material, whereas metathesis would rearrange the original beads and deletion would remove one.''')
put('epiphenomenon','A dependent appearance raises a question about causal return.','A lower mechanism gives rise to an upper halo through one-way links, separating dependence from reciprocal influence.',
'''DRAW THE CAUSAL CLAIM|Represent the proposed relation with arrows: the underlying process produces the secondary event. Then ask whether an arrow returns. Ordinary uses may leave that question open; strong epiphenomenalism denies a relevant return influence. A causal diagram forces the speaker to state which claim is actually being made.''',
'''INDICATION IS NOT CONTROL|A visible indicator can help an observer predict a process without itself controlling the process. That epistemic usefulness differs from causal efficacy. The distinction complicates the word secondary: something may matter greatly as evidence or experience even if a theory denies it a particular causal role.''',
'''Imagine an instrument display whose pattern reliably varies with a hidden process. Reading the display may be useful, but usefulness to an observer does not determine the display's physical influence on what it measures. Real instruments may interact with their targets in complicated ways, so the example raises a question rather than furnishing a universal case of causal impotence.

In philosophy of mind, the stakes are different and stronger. An epiphenomenalist account must explain how mental events depend on physical events while denying certain causal effects in return. Questions about the apparent role of pain, deliberation, and reports of experience then become pressing. Naming the doctrine does not resolve those objections, nor does a decorative halo count as evidence for it.

A useful reading exercise underlines every causal verb in a passage: produces, accompanies, indicates, explains, changes. These verbs are not interchangeable. If an author calls a phenomenon epiphenomenal, identify the underlying process and the denied influence. If either remains unspecified, the word may be functioning as a vague dismissal instead of a precise causal claim. The diagrammatic sculpture makes that demand for explicit relations visible.''')
put('episteme','What can appear as knowledge has conditions.','The same colored items are reorganized by different divisions, showing a change in the framework of classification.',
'''WHEN THE TABLE CHANGES|Adding a specimen to an existing classification differs from changing the relations by which specimens become comparable. The sculpture keeps its elements recognizable while rotating the organizing divisions. It asks whether historical change affects only the contents of knowledge or also the rules that make those contents intelligible.''',
'''READ ACROSS PRACTICES|A single unusual opinion cannot establish an episteme. An archaeological inquiry examines relations among statements, disciplines, and practices across a historical field. Look for what questions become possible, which distinctions organize evidence, and which objects of inquiry emerge, rather than hunting for one secret sentence everyone believed.''',
'''Two natural histories might describe the same organism yet organize its significance differently. One may emphasize visible resemblance and placement in an ordered table; another may relate form to historical development and relations of life. The contrast is not merely that the later writer has collected more facts. What counts as a pertinent relation may have changed.

This simplified example introduces Foucault's question without proving any particular historical division. His analyses require detailed engagement with archives and disciplinary practices. An episteme should not become a fashionable synonym for era, ideology, or collective psychology. Those terms can intersect with the inquiry, but they do not automatically name the same object.

For practice, compare two textbook classifications separated by a substantial interval. Note which categories persist, which disappear, and which new relations become central. Then distinguish changes in terminology from changes in the conditions of explanation. The exercise should also leave room for discontinuity and unevenness: different practices do not necessarily transform on one synchronized calendar. The ancient meanings of epistēmē remain distinct from this later archaeological use, so identifying the author and intellectual setting is part of reading the word accurately.''')
put('epizeuxis','The next word is the same word, again.','Three neighboring bells preserve identity and adjacency, turning immediate recurrence into a visible pulse.',
'''PACING MAKES THE PRESSURE|Read no, no, no quickly, then with long pauses. The sequence remains epizeuxis, but its force can shift from urgent refusal toward exhausted disbelief. Written adjacency identifies the figure; performance supplies duration, breath, and changing stress that prevent repeated wording from becoming emotionally identical.''',
'''REPETITION CAN EXPOSE FAILURE|A speaker may repeat because one utterance seems insufficient to meet an event. The recurrence then reveals the limits of language as well as its power. In a comic setting, the same insistence can become disproportionate, allowing a listener to hear the gap between feeling and occasion.''',
'''A word repeated immediately does not pass through the substantial intervening material that gives epanalepsis its characteristic return. Instead, the interval itself becomes expressive. A pause can feel like an attempt to recover breath, a renewed demand, or a mechanical beat. Typography may suggest such timing but cannot fully prescribe a spoken performance.

The three bells are deliberately alike. Their identity represents repeated wording, while the imagined act of striking them introduces a temporal dimension that a still image cannot contain. One could strike them faster, softer, irregularly, or with increasing force. Each performance would retain the structural recurrence while changing its emotional interpretation.

For practice, write a short scene containing the same repeated word in two speakers' mouths. Give one speaker relief and the other suspicion without changing the repeated form. Let context and surrounding action do the work. Then remove the context and notice how much interpretive certainty disappears. This exercise resists the habit of assigning a fixed emotion to a rhetorical label: epizeuxis names a pattern of immediate recurrence, while the scene gives that pattern its human stakes.''')
put('equifinality','The same ending can conceal different beginnings.','Distinct trajectories reach a shared terminal chamber without losing the differences in their routes.',
'''THE INVERSE PROBLEM|An outcome alone may not reveal the path that produced it. Two organizations can achieve similar retention rates through different policies and cultures. Working backward from the result therefore requires additional evidence; equifinality explains why a persuasive single origin story can outrun what the observed endpoint establishes.''',
'''TRANSPORTING A SUCCESS|A successful method may depend on local resources, interactions, and timing. If several routes reach a similar outcome, copying one route elsewhere is not automatically optimal. Compare mechanisms and constraints before turning a successful case into a universal recipe; convergence of results does not erase differences in feasibility.''',
'''Suppose two schools improve attendance. One changes transport arrangements; another changes schedules and family communication. Similar aggregate improvement does not establish that both used the same mechanism, nor does it imply that either approach will work unchanged in a third setting. The shared outcome is a starting point for explanation rather than its completion.

Equifinality is useful precisely because it challenges simplistic one to one mappings without denying causation. The paths may be identifiable and strongly constrained. Some combinations of conditions may work; others may fail. The concept says that more than one route can reach an outcome, not that all imaginable routes are equally effective or that mechanisms no longer matter.

For practice, identify a result and propose two genuinely different pathways to it. Specify the conditions each pathway requires, then name evidence that would distinguish them retrospectively. Finally, reverse the question and consider how the same starting conditions might produce different outcomes. That reverse direction introduces multifinality. Keeping the two concepts separate clarifies whether the analytical difficulty concerns many roads to one destination or divergent destinations from apparently similar beginnings.''')
put('eschaton','An ending imagined as the fulfillment of time.','A worn path approaches a luminous nested threshold, replacing mere stoppage with a question of consummation.',
'''THE FUTURE ORGANIZES THE PRESENT|An anticipated ultimate end can shape how present actions, suffering, and obligations are interpreted. The eschaton thus functions as a horizon of significance, not just a distant scheduled event. Different traditions draw very different consequences from that horizon, so its ethical implications must be examined rather than assumed.''',
'''AFTER THE LAST DATE|A calendar can represent sequence but cannot by itself explain fulfillment, judgment, or transformation. Ask what a particular account claims will end and what relation survives that ending. The sculpture's threshold invites those questions without declaring that every religious or secular framework shares one promised final condition.''',
'''The final page of a calendar is a limit imposed on a sequence of dates. An eschatological consummation may instead claim to disclose what the sequence means. This distinction explains why the eschaton can involve judgment or renewal rather than simple cessation. The interpretation depends on a tradition's account of history, persons, and ultimate reality.

Secular narratives can also organize history around a projected final condition, but applying theological vocabulary to them requires care. A political forecast, a technological prediction, and a religious promise do not become identical merely because each looks toward a transformed future. The comparison becomes useful when it specifies the structure of expectation and the authority claimed for it.

For a reading exercise, examine a passage about the end of history or the last things. Separate prediction, promise, warning, and interpretation. Ask whether the author describes another event within ordinary time or a transformation of the order by which events receive meaning. Then consider how the imagined ending changes obligations in the present. The quiet architecture in the artwork deliberately avoids equating ultimate significance with the visual spectacle of destruction.''')
put('eucatastrophe','Joy arrives where the story had nearly exhausted hope.','A falling ribbon turns upward where an arriving strand meets it, marking sudden deliverance at the point of collapse.',
'''REREADING THE PREPARATION|After a joyous reversal, earlier details may acquire new significance. A remembered kindness or an overlooked alliance can make deliverance feel surprising without feeling arbitrary. The reader's second pass discovers a route toward hope that the first pass, occupied by danger, could not fully recognize.''',
'''JOY KEEPS THE Wound|The turn does not erase the cost of reaching it. Relief gains depth because suffering remains part of the story's reality. Compare a reversal that acknowledges losses with one that declares them meaningless; eucatastrophic joy can answer catastrophe without pretending that catastrophe never had its claim.''',
'''A narrative can end happily without staging the sudden turn Tolkien's word emphasizes. Conversely, a moment of deliverance may arrive before a long and difficult aftermath. The concept concerns the quality of an unexpected joyous reversal, especially within the imaginative conditions of fairy stories, rather than a simple tally of favorable events on the final page.

The distinction from deus ex machina requires nuance. One term can describe the thematic or emotional character of deliverance, while the other often criticizes the mechanism by which a plot resolves its difficulty. The same ending could be evaluated along both dimensions. Calling a turn eucatastrophic does not exempt it from questions about preparation and narrative coherence.

For practice, reread a story whose rescue once surprised you. Mark the earlier details that support the turn and the losses that remain afterward. Ask whether the renewed possibility changes the meaning of preceding suffering or simply ignores it. The sculpture's rising gold continuation remains attached to the descending path: the change is powerful because the approach to disaster stays materially present, rather than being replaced by an unrelated decorative flourish.''')
put('exaptation','A useful inheritance acquires another use.','Related feather structures appear in different functional relations, preserving material continuity while changing the role.',
'''PRESENT BENEFIT, PAST ORIGIN|To explain why a trait is useful now is not yet to explain why it arose. A historical account needs evidence that separates earlier conditions from later recruitment. Comparing related organisms and preserved structures can help test that account, whereas a convenient story about present usefulness cannot establish it.''',
'''FUNCTIONS CAN ACCUMULATE|Cooption need not abolish an earlier role. A structure can contribute to several functions, and later selection can refine a newly acquired one. The important distinction concerns historical relations among origin, recruitment, and subsequent modification; those relations may be complex rather than a neat switch between two exclusive purposes.''',
'''Imagine an architectural alcove built for storage and later used to improve acoustics. The example makes changed use intuitive, but deliberate human repurposing is only a metaphor for biological exaptation. Evolutionary histories do not require an inventor who foresees a new role. Variants, inherited structures, environmental conditions, and selection operate without that kind of planning.

The feather example likewise demands careful wording. Feathers preceded powered flight, but reconstructing their earlier roles involves evidence and continuing inquiry. A familiar classroom illustration should not harden into a claim that every relevant lineage followed one perfectly known functional sequence. Different traits can have multiple effects, and subsequent adaptations may alter structures after recruitment.

For practice, distinguish three claims about a feature: what it currently does, when that role became important, and how the feature originally arose. List the evidence each claim would require. If the same present observation is being used to settle all three, the historical inference needs further support. The paired feather sculptures retain their branching material form while altering the surrounding relations that make a particular function visible.''')
put('exergue','A marginal field that can govern the reading of the whole.','A medal’s separated lower compartment is enlarged beside the principal relief, giving its marginal position interpretive weight.',
'''SMALL FIELD, LARGE CONSEQUENCE|A date or mint indication beneath a design may change how an object is attributed and understood. Visual prominence and evidential importance need not coincide. The enlarged compartment asks the viewer to inspect the apparent margin as part of the object's information architecture rather than as leftover space.''',
'''FROM COIN TO THRESHOLD|An introductory quotation can orient a reader before the main argument begins. In the extended literary sense, exergue names this preliminary placement. Compare the quotation's promised frame with the work that follows; the relation may be confirmation, complication, irony, or an invitation that the text later resists.''',
'''The numismatic sense is spatially specific. On many coins or medals, the exergue occupies a field below the principal design, often separated by a line. A border, rim, or any empty patch should not automatically receive the name. Identifying the compartment accurately helps prevent a picturesque term from replacing careful description.

The artwork deliberately leaves its surfaces without fabricated inscriptions. Its lower strokes indicate texture and division, not a claim to reproduce a historical mint mark. This restraint keeps the conceptual sculpture separate from documentary numismatics, where letter forms, wear, provenance, and exact placement can be crucial evidence.

For practice, compare the main image and marginal information on an actual object, or compare a book's epigraph with its opening paragraph. Ask which element first attracts attention and which most strongly constrains interpretation. A modest date can reorganize the meaning of an imposing image; a short prefatory quotation can prepare a question the entire work must confront. The shared principle is not that all margins contain hidden truth, but that placement and scale do not settle interpretive importance in advance.''')
put('exophora','The sentence reaches beyond the sentence.','A directional strand leaves the bounded page and terminates at an object in the surrounding space.',
'''A PERFECT TRANSCRIPT CAN FAIL|A transcript may preserve put that over there exactly while losing the gesture and shared visual field that made the instruction usable. Accuracy of wording is therefore different from completeness of communicative context. Recording an exchange sometimes requires describing the environment as well as transcribing the spoken words.''',
'''CONTEXT MUST BE SHARED|A speaker can assume a referent is visible when the listener cannot see it. The resulting misunderstanding concerns access to the situation, not necessarily grammar or vocabulary. Ask what participants can perceive and jointly identify before deciding that an exophoric expression has successfully picked out its object.''',
'''An instruction such as take that one may be perfectly clear at a market stall and almost useless in an isolated transcript. The missing information is not necessarily another sentence. It may be a gesture, a visible object, or a shared task that makes one candidate salient. Exophora describes this outward dependence of reference.

Technology often exposes the dependence. A person screen sharing may say click here while the pointer is hidden from the remote viewer. The expression has not become grammatically defective; the participants no longer share the environmental cue on which its successful interpretation depends. Adding a location description can repair the communication by bringing more information into discourse.

For practice, transcribe a short instruction from an everyday exchange and remove its setting. Identify each expression that becomes ambiguous. Then restore only the minimum contextual information required to resolve it. This distinguishes situational reference from backward reference to a mentioned noun. It also shows why exophora and deixis overlap without being identical: one classifies where the referent is supplied, while the other concerns interpretation relative to a contextual center. The artwork makes the page's boundary conspicuous so the directional crossing can be read.''')
put('facticity','Every possibility begins somewhere already given.','A figure stands on a rooted platform from which unequal routes depart, retaining the material conditions of any choice.',
'''THE STARTING POINT HAS WEIGHT|Two people can consider the same project while facing different material possibilities because of their situations. Calling both choices free does not make their constraints equivalent. An account of facticity needs concrete conditions rather than a generalized celebration of decision; the particular stairs and thresholds actually matter.''',
'''INTERPRETATION MEETS RESISTANCE|A circumstance can acquire different meanings through projects without becoming infinitely malleable. A locked door may be obstacle, protection, or challenge, yet its physical and institutional constraints remain consequential. Reading facticity alongside possibility means holding that interpretive openness together with the world's capacity to resist what one intends.''',
'''Consider someone who inherits a workshop. Its tools, debts, location, and family associations are given conditions of the situation, but none individually dictates a complete life. Selling it, continuing the trade, changing its use, or leaving it unused would each interpret the inheritance through a project. Some possibilities may nevertheless be unavailable because of law, money, health, or obligation.

This example helps distinguish situated freedom from the claim that attitude alone removes constraints. It also avoids the opposite claim that circumstances write an entirely finished script. Existential accounts investigate the tension, though Sartre's vocabulary and Heidegger's account of factical existence should not be treated as interchangeable systems.

For practice, describe a decision first as a list of external facts and then from the standpoint of the person who must act. Notice how relevance changes: an ordinary stair can become a decisive barrier, an accent a social vulnerability, or an inherited object a summons. The second description does not replace factual accuracy with fiction. It asks how conditions are lived as a situation. The sculpture's divergent paths remain attached to their starting platform because possibilities do not originate nowhere.''')
put('fissiparity','A division that becomes another viable beginning.','A whole, a constricted division, and two renewed forms distinguish reproductive fission from mere fragmentation.',
'''DIVISION IS ONLY PART|Separating a body is insufficient if the resulting parts cannot become viable individuals. The reproductive meaning therefore includes what follows the split. The sequential image makes regeneration and continued organization central, preventing the dramatic moment of separation from standing in for the entire biological process.''',
'''A POLITICAL METAPHOR HAS LIMITS|Calling an organization fissiparous emphasizes repeated splitting, but committees do not reproduce through the same mechanisms as organisms. The metaphor can sharpen attention to multiplication while concealing losses of coordination or purpose. Test which relations survive the comparison before treating division as either healthy growth or inevitable decay.''',
'''The image arranges three stages so that the final pair matters as much as the constricted middle. A reproductive process must be understood through viable continuation, not merely through the visible fact that one form has become two pieces. This distinguishes the relevant biological use from arbitrary damage or unsuccessful fragmentation.

Planarians provide accessible examples, but their reproductive patterns vary among species and conditions. A generalized sculpture cannot identify a particular organism or guarantee that every cut would lead to regeneration. Its role is to clarify the relation between fission and new individuals while leaving detailed biology to species specific evidence.

For an interpretive exercise, compare descriptions of biological fission and organizational factionalism. Both can involve increasing the number of units; their standards of viability, mechanisms, and consequences differ. Ask whether the figurative use explains anything beyond the outline of splitting. A party may gain several names while losing capacity to act together, whereas biological reproduction has its own criteria of successful continuation. The word becomes more exact when its shared geometry is allowed to invite comparison without dictating an identical account of what life or success means in each setting.''')
put('fulguration','An instant of brilliance is not yet a lasting explanation.','A branching flash exposes a low field of forms for one imagined instant before darkness reclaims the scene.',
'''VISIBILITY IN A FLASH|Lightning can disclose many details at once without giving an observer time to arrange them into a stable account. The metaphor of fulguration therefore joins revelation to brevity. Ask what becomes perceptible in the instant and what must still be reconstructed after the illumination has passed.''',
'''INSIGHT NEEDS AN AFTERLIFE|A sudden idea may feel complete because it arrives forcefully. Testing it requires slower work: articulation, comparison, and examination of consequences. The flash can begin inquiry without completing it. The sculpture preserves the branching instant while the explanation asks what evidence would justify its apparent revelation.''',
'''A flash has a peculiar relation to memory. It may leave an afterimage more intense than the observer's ordinary perception, yet intensity does not guarantee completeness. Details glimpsed simultaneously can become difficult to place once the scene returns to darkness. Literary uses of fulguration often draw energy from this combination of disclosure and disappearance.

The metaphor extends naturally to insight, but an experience of understanding and a justified explanation are different achievements. An idea can arrive abruptly and still require revision. The word is strongest when it preserves the event's suddenness without treating suddenness as a certificate of truth.

For practice, describe a moment of apparent realization in two stages: the instantaneous impression and the later account that tests it. Identify what the second stage adds, qualifies, or abandons. This exercise gives the metaphor an epistemic consequence rather than leaving it as ornamental lightning. The medical meaning remains separate: it concerns a particular technique involving electrical discharge at tissue surfaces. Nothing in the sculpture or poetic explanation should be read as a procedural description or a reason to conflate every electrical treatment under the same label.''')
put('gnosis','Knowledge described as a transformation of the knower.','A newly perceived inner doorway changes the relations among familiar objects within the same chamber.',
'''KNOWING ABOUT AND KNOWING AS|A tradition may distinguish repeating a teaching from undergoing the recognition the teaching concerns. That distinction explains why gnosis is sometimes described as transformative. The analyst can accurately describe the claimed difference while keeping separate the historical study of a tradition and the endorsement of its metaphysical commitments.''',
'''ASK WHO USES THE NAME|The category Gnostic groups diverse materials and has a contested scholarly history. Before generalizing, identify the text, community, and account of liberation in question. A shared vocabulary of hidden knowledge may conceal major differences in cosmology, practice, authority, and the relation between the human and the divine.''',
'''Learning the layout of a room differs from discovering that a familiar wall contains a door. In the latter case, the same objects can acquire different relations: enclosure becomes passage, and a boundary becomes a possible exit. The sculpture uses this difference as a metaphor for transformative recognition, not as evidence for any supernatural claim.

Religious uses of gnosis may concern a person's origin, condition, and possibility of liberation. Those claims must be read in their specific textual and historical settings. Treating the word as a generic label for occult secrets removes precisely the content that distinguishes one account from another. Treating it as mere intelligence loses the proposed change in the knower's relation to reality.

For practice, read a passage that distinguishes ordinary information from saving or transformative knowledge. Identify what must be known, who can know it, how it is acquired, and what it is said to change. Then separate the participant's claim from the historian's description. This method permits sympathetic interpretation without automatic assent or dismissal. The hidden doorway becomes useful only when its promised significance is specified; the bare fact of secrecy would explain very little.''')
put('hendiadys','One conception takes the grammatical shape of two.','Two differentiated ribbons form one draped structure, preserving coordination while producing a shared whole.',
'''TRY THE SUBORDINATE VERSION|Transform a proposed hendiadys into a noun with a modifier, then compare the result. Welcome and warmth might become warm welcome in an appropriate context. The paraphrase exposes the conceptual relation, but the coordinated version can distribute emphasis and duration differently; grammatical economy is not the only literary aim.''',
'''DO NOT COUNT THE CONJUNCTIONS|Bread and butter may name two independent items in one context and a conventional combined provision in another. The presence of and does not settle the analysis. A persuasive hendiadys reading must explain why the pair expresses one complex idea and what the coordination contributes to its presentation.''',
'''The phrase's two grammatical members can give an idea more room to unfold than a compact modifier construction would allow. Instead of immediately subordinating warmth to welcome, coordination lets each term sound momentarily independent. Context may then gather them into one conception. This balance between syntactic equality and semantic unity is the figure's central tension.

Not every coordinated pair that feels closely associated is therefore an uncontested example. Rhetorical analysis depends on what relation the passage invites, and classifications can vary. The famous or familiar status of a phrase does not remove the need to explain its actual construction. A good reading should make clearer why the form matters, not merely attach a rare label.

For practice, write one pair as simple enumeration and use the same pair in a sentence that encourages a single complex meaning. Then paraphrase the second with subordination. What disappears: rhythm, openness, delay, or emphasis? The sculpture's two ribbons retain distinguishable colors even as they form one drape. Their relation is neither duplication nor total fusion, just as hendiadys lets a single conception speak through two coordinated terms without making the second word redundant.''')
put('heterotopia','A real site organizes a different relation to other sites.','Garden, ship, archive, and memorial share a regulated architectural frame while retaining different temporal and social relations.',
'''ENTRANCE IS AN ARRANGEMENT|A site's difference is often maintained by rules of admission, ritual, schedules, or institutional boundaries. A museum ticket and a prison gate organize access very differently. Studying those arrangements prevents heterotopia from becoming a vague label for any unusual place with an attractive or disorienting atmosphere.''',
'''SEVERAL TIMES IN ONE PLACE|An archive or museum can gather objects from incompatible periods within a present institution. Their juxtaposition does not abolish history; it creates a specific relation to accumulation, preservation, and display. Ask how the site's temporal arrangement relates to the ordinary spaces and practices surrounding it.''',
'''A cemetery is located within a society while arranging a distinctive relation to bodies, memory, property, and time. Its significance comes from those relations, not simply from looking unusual. Similarly, a ship can connect distant places while organizing a bounded world of movement, labor, and access. Foucault's examples invite relational analysis rather than a checklist of picturesque locations.

The concept's formulations and subsequent uses vary, so applications require argument. Calling an imaginary room heterotopic because it juxtaposes surprising objects may miss the emphasis on real sites and their social arrangements. Conversely, a materially ordinary institution can produce highly distinctive spatial and temporal relations through its rules.

For practice, choose a museum, cemetery, or other site and describe its entrances, authorized activities, temporal rhythms, and relation to surrounding places. Then ask what the term helps explain that a description of unusual architecture would not. The artwork compresses several functions beneath one roof as an analytical model. It does not propose that every museum literally contains all these spaces or that institutional difference is automatically liberating. A site can contest an order while also regulating, excluding, or confining its participants.''')
DATA['eucatastrophe']['s4']=DATA['eucatastrophe']['s4'].replace('JOY KEEPS THE Wound','JOY KEEPS THE WOUND')
