import json, re
from pathlib import Path

OUT=Path('/tmp/memoryx-word-atlas23/group-a')
NOTES=Path('/Users/abhay.singh/Downloads/MemoryX/word-atlas-23/notes')

ENTRIES=[
dict(index=1,slug='aporia',word='APORIA',pronunciation='uh-POR-ee-uh',tagline='The passage that thinking cannot find',
definition='Aporia is a condition of reasoned perplexity: inquiry discovers apparently compelling claims that cannot readily be reconciled, leaving the thinker without an evident passage to a defensible conclusion.',
etymology='From Greek aporia, difficulty or lack of passage, formed from a negative prefix and poros, a passage or way. Its philosophical force preserves that spatial image: thought reaches a place where its familiar routes cease to lead onward.',
sections=[
dict(heading='An earned impasse',text='An aporia need not be mere ignorance. Someone who has never considered justice lacks an answer; someone who tests several plausible definitions and finds each inadequate has acquired a structured difficulty. The obstruction is a result of inquiry, and therefore contains information about its assumptions.'),
dict(heading='The Socratic pressure',text='Several early Platonic dialogues end without a settled definition of the virtue under examination. Such endings expose confidence that outruns understanding. They can invite continued inquiry, although scholars disagree about whether particular dialogues conceal positive conclusions beneath their explicit failure to reach agreement.'),
dict(heading='Contradiction is insufficient',text='Two sentences can contradict because one contains a simple mistake. An aporia becomes philosophically interesting when the opposed commitments each retain a serious claim on us. The task is then to revise distinctions, premises, or expectations, rather than celebrate contradiction as a revelation in itself.'),
dict(heading='Living with the blockage',text='Later philosophical uses can make aporia more enduring than a puzzle awaiting a solution. Nevertheless, suspension of certainty does not require suspension of every action. One may decide provisionally while acknowledging that the reasons available do not dissolve the underlying difficulty or guarantee the decision.')],
literary='At the nowheregate, where every why had borrowed its key from the lock it promised to unfasten, the walker stood passagepoor, listening to two truthful roads explain why neither could be taken.',
art_caption='Concentric passages promise an entrance, then end against one another: the maze makes the failure of a route visible.',accent='D9AC78',theme='201A32',
extra='''Consider a familiar problem: must a just person always repay a debt? Repayment seems central to fairness. Yet returning a borrowed weapon to a friend who now intends immediate violence seems wrong. The example, associated with the opening discussion of justice in Plato’s Republic, does not prove that fairness is meaningless. It shows that an attractive definition leaves out morally relevant circumstances. A reader can escape this first blockage by adding a qualification, but the qualification must itself withstand examination. Philosophical progress often consists in improving the shape of a difficulty before obtaining a satisfactory answer.

There are several possible responses. Reject one premise; show that the apparent conflict trades on two meanings of a term; deny that the offered alternatives exhaust the possibilities; or accept that the evidence cannot yet decide. These are different intellectual acts, and the word aporia should not blur them. Calling a disagreement aporetic does not automatically ennoble it. A computational error, an equivocation, and a deep conflict between values require different repairs.

Aristotle frequently treats the collection and examination of puzzles as preparatory work for inquiry. The beginning of Metaphysics Book Beta supplies an especially explicit example of this method. Aporia here belongs to the workshop of investigation. In some modern and contemporary philosophy, by contrast, it can name a structural difficulty that resists final closure. Those uses share a concern with blocked passage, but they are not a single doctrine transmitted unchanged across centuries.

The literary sentence gives every explanation a circular dependency: the key comes from the very lock it is supposed to open. The two roads embody reasons that remain credible but do not jointly authorize a route. “Passagepoor” condenses the etymological image; it is an invented expression, not a historical translation. The walker has learned something precise about the limits of the map.

For further reading, try Plato’s Meno and Euthyphro, then the opening of Aristotle’s Metaphysics Book Beta. They make useful companions because perplexity plays different roles in each. The illustration is locally rendered and metaphorical: a blocked labyrinth pictures intellectual difficulty without claiming that all philosophical problems have a single exit.'''),
dict(index=2,slug='apophasis',word='APOPHASIS',pronunciation='uh-POF-uh-sis',tagline='Saying through the shape of refusal',
definition='Apophasis names rhetorical mention through professed omission, and, in a broader philosophical and theological register, discourse that approaches its subject by denying inadequate descriptions rather than confidently assigning positive predicates.',
etymology='Greek apophasis means denial or negation and is associated with apophanai, to deny. English usage develops related but distinct rhetorical and theological senses. The shared vocabulary of negation should not erase the different purposes served by these practices.',
sections=[
dict(heading='The denial that advertises',text='“I shall not discuss your repeated lateness” has already introduced repeated lateness into the discussion. In rhetorical usage, apophasis overlaps with terms such as paralipsis and praeteritio. Terminology varies among handbooks, but the conspicuous pretense of omission is the central mechanism in this familiar sense.'),
dict(heading='Negative theological speech',text='Apophatic theology questions whether ordinary predicates adequately describe the divine. Saying that God is not finite, or not an object among objects, can discipline misleading images. This is a family of approaches within particular traditions, not an empirical procedure that establishes the existence of its subject.'),
dict(heading='Absence still has edges',text='Negation remains dependent on what it denies. To say that something is not measurable still introduces measurement as a relevant frame. Some apophatic writing consequently qualifies or negates its own negations, resisting the temptation to make a final, positively graspable object out of verbal refusal.'),
dict(heading='Two uses, different stakes',text='A politician who disclaims an accusation may be maneuvering to make it memorable. A theological writer who refuses a description may be trying to restrain false confidence. The linguistic resemblance matters, but intention, context, and argumentative function prevent the two cases from becoming interchangeable examples.')],
literary='I will not name the nameless, said the namewright, nor measure its unmeasured margin, while each unspoken syllable, loudly absent, built another gilded railing round the nothing he had sworn to leave unbuilt.',
art_caption='A polished, interrupted halo gives elaborate form to an empty center, showing how refusal can frame what it cannot present.',accent='C9B6ED',theme='201A32',
extra='''Suppose a candidate says, “I refuse to bring up my opponent’s disastrous accounting.” The refusal is part of the act of bringing it up. Listeners receive the allegation while the speaker adopts the posture of someone exercising restraint. This does not require the allegation to be false, but it can weaken accountability for having introduced it. A useful practical response is to separate the surface refusal from the proposition that the audience has nevertheless been invited to remember.

Now compare a theologian who writes that the divine is not a body. Here the negation may aim to remove a misleading category rather than plant an insinuation. In the works associated with Pseudo-Dionysius, negation belongs to an ascent beyond the adequacy of ordinary affirmation and denial. Readers should not reduce this to a claim that God simply has no properties, nor assume that every religious tradition understands negative language in the same way. Historical commitments determine what is being denied and why.

There is also an important logical distinction. The assertion that a description fails is not equivalent to a successful description of what replaces it. If a witness says an unfamiliar sound was neither a bell nor a whistle, we have narrowed the options without identifying the source. Negative information can be useful and incomplete at the same time. Apophatic practice becomes philosophically demanding when it also doubts the adequacy of the conceptual field in which those alternatives were formed.

The original literary sentence dramatizes this difficulty. The “namewright” is a maker of names who tries to work by refusing his own craft. Every omitted syllable becomes a railing: an apparent withdrawal adds another conceptual boundary. The sentence leaves open whether these boundaries guide attention responsibly or merely decorate an absence. Its invented word and self-cancelling clauses are literary devices, not claims about the word’s historical morphology.

Read Pseudo-Dionysius’s Mystical Theology for one influential theological development, and compare rhetorical treatments of paralipsis or praeteritio in a reputable rhetoric handbook. The illustration is locally rendered and metaphorical. Its empty center is neither a portrait of the divine nor proof of an ineffable object; it pictures the way elaborate surrounding speech can call attention to what it declines to fill.'''),
dict(index=3,slug='anagnorisis',word='ANAGNORISIS',pronunciation='an-ag-NOR-ih-sis',tagline='Recognition rewrites what came before',
definition='Anagnorisis is a decisive recognition, especially in narrative: a movement from ignorance to knowledge that discloses identity, relationship, or circumstance and changes how characters understand their situation and earlier events.',
etymology='The word comes from Greek anagnorisis, recognition, associated with anagnorizein, to recognize. Its influential critical use derives from Aristotle’s Poetics, where recognition is discussed as a component of tragic plotting and its transformations of human relationships.',
sections=[
dict(heading='More than fresh information',text='Discovering the time of a train adds a fact. Discovering that the stranger you condemned is your brother reorganizes a relationship, its obligations, and the meaning of previous actions. Narrative recognition matters because what becomes known changes the structure of the situation for its participants.'),
dict(heading='Recognition and reversal',text='Aristotle distinguishes recognition from reversal, or peripeteia, while admiring their conjunction in especially effective plots. Knowledge can arrive as fortune turns, but the two movements are not identical. A character may understand the truth without escaping the consequences already set in motion by earlier ignorance.'),
dict(heading='The backward illumination',text='A convincing recognition can make earlier details legible in a new way. A gesture once read as hostility becomes protection; a coincidence becomes a clue. The past has not physically changed. Its place within the reader’s or character’s explanation has changed, sometimes with devastating ethical force.'),
dict(heading='Earned and manufactured discovery',text='Tokens, testimony, reasoning, and unfolding action can all produce recognition. Their dramatic effectiveness depends on how the discovery grows from the work. An arbitrary final revelation may surprise without satisfying, while a well prepared recognition can feel both unforeseen and retrospectively required by the evidence.')],
literary='When the stranger’s scar unlettered the father from the foe, all yesterday’s harmless doorways opened inward upon the same withheld room, and the son discovered that arriving was the oldest form of having already been there.',
art_caption='A fractured outer shell releases a luminous core; the revealed center reorganizes the surrounding fragments into a newly intelligible whole.',accent='E8BE80',theme='201A32',
extra='''Imagine a story in which a courier repeatedly obstructs a young investigator. At first the interruptions appear self-serving. Late in the story, the investigator discovers that the courier is protecting an endangered witness. The same actions now belong to a different causal and moral account. If the revelation is supported by earlier details, readers can reconstruct the clues rather than merely accept a new instruction from the author. Recognition is therefore a redistribution of significance as well as an acquisition of information.

The classical example of Oedipus is more severe. Investigation brings knowledge of relations and actions that were already real while their agent remained ignorant of them. Recognition does not manufacture guilt, erase responsibility, or settle every interpretation of responsibility. It brings a person into a changed relation with facts that the plot has made consequential. Sophocles and Aristotle should not be treated as offering an identical philosophical account merely because Aristotle discusses the tragedy.

A reader’s recognition and a character’s recognition may also occur at different times. Dramatic irony arises when an audience understands a situation that remains hidden from a participant. Suspense may then concern the arrival of knowledge rather than the discovery of the underlying fact. Conversely, a narrator can delay the reader’s recognition after a character has already understood. Describing precisely who knows what, and when, prevents the term from becoming a vague synonym for any dramatic surprise.

Recognition can fail. A character may seize on a misleading token, invent a relationship, or mistake the shape of an explanation for its truth. Literature can stage this false recognition deliberately. Outside fiction, the feeling that everything suddenly makes sense supplies no guarantee that the explanation is correct; evidence still matters.

In the dense sentence, a scar changes “foe” into “father,” while the doorways represent previously disconnected clues. The withheld room is a single explanation that recasts them. The paradox of arrival names belated knowledge of a relationship that predates its discovery. Read Aristotle’s Poetics alongside Sophocles’s Oedipus Tyrannus for central examples and useful disagreements. The locally rendered illustration uses an opening shell as a metaphor for recognition; it is not a model of how memory or perception literally works.'''),
dict(index=4,slug='anacoluthon',word='ANACOLUTHON',pronunciation='an-uh-kuh-LOO-thon',tagline='The sentence changes its mind midway',
definition='Anacoluthon is a disruption of expected grammatical sequence: a sentence begins with one construction but continues with another, leaving its opening syntactically unfulfilled or altering the relationship that the beginning led us to expect.',
etymology='From Greek anakolouthon, lacking sequence or consistency, built from a negative prefix and akolouthos, following. The grammatical term names a failure of expected following, rather than every interruption, fragment, surprising image, or change of subject in discourse.',
sections=[
dict(heading='A broken grammatical promise',text='“The person who took my coat—well, I hope it keeps them warm” begins as though a subject will receive a matching predicate, then restarts with another subject. Meaning remains recoverable, but syntax records the change of plan instead of concealing it within a smoothly completed construction.'),
dict(heading='Speech under pressure',text='Conversation is planned while it happens. Speakers revise intentions, retrieve missing words, and respond to interruptions before a sentence is complete. Anacoluthon can preserve this pressure in writing, suggesting agitation, intimacy, distraction, or a mind discovering its thought at the same moment that it speaks.'),
dict(heading='Related but different figures',text='Aposiopesis breaks off speech, often leaving something unsaid. Anacoluthon may continue at length after abandoning its initial construction. A parenthesis, meanwhile, can interrupt a sentence without damaging its grammar. These distinctions make it possible to describe the actual formal event rather than merely label expressive irregularity.'),
dict(heading='Design and accident',text='The same syntactic discontinuity may be a deliberate literary effect or an editing problem. Intention cannot reliably be inferred from the break alone. Readers must consider genre, voice, surrounding patterns, and the work’s treatment of attention before deciding what interpretive weight a particular disruption can bear.')],
literary='The sentence that would have brought him safely through the doorway of his explanation—well, the kettle was screaming, and tomorrow, if she remembered, nobody had ever asked which silence he meant to return.',
art_caption='One continuous tube halts abruptly; a differently aligned strand resumes the motion without completing its original route.',accent='89C7D9',theme='201A32',
extra='''A useful diagnostic procedure is to stop at the opening clause and predict the construction it appears to require. In “The person who took my coat,” the noun phrase prepares us for a predicate about that person. When the continuation becomes “I hope it keeps them warm,” a new independent clause has taken over. The earlier phrase may still function conversationally as a topic, but the sentence no longer follows the grammatical path its opening strongly suggested. Different grammatical theories can describe such topic structures differently, so a stylistic judgment should not pretend that every case is uncontested.

Compare “The person who took my coat, despite my repeated requests, has not returned it.” The parenthetical interruption delays the predicate but leaves the original construction intact. Compare also “If I ever find the person who took my coat—”. That utterance breaks off without adopting a replacement construction and is a clearer candidate for aposiopesis. These are nearby possibilities, not mechanically exclusive boxes; a literary passage can use more than one kind of disruption.

The effect depends on proportion. A single break in otherwise measured prose can mark an emotional threshold. Repeated breaks can establish a speaking consciousness whose attention wanders, defends itself, or continually revises its account. They can also simply exhaust a reader. Calling an awkward sentence anacoluthon describes a formal possibility; it does not certify artistic success or rescue writing from the need to communicate.

The invented literary example launches “The sentence that would have brought him” and then abandons its promised predicate. The kettle introduces a practical interruption, while tomorrow and silence pull the continuation into incompatible temporal and emotional directions. Its confusion is purposeful, but the initial syntactic break is identifiable independently of the surrounding surrealism. A bizarre image in a grammatically complete sentence would not establish the same figure.

For orientation, consult a substantial rhetoric reference such as Richard A. Lanham’s A Handlist of Rhetorical Terms, then examine carefully transcribed conversation alongside literary monologue. Read examples in context rather than treating every dash as proof. The locally rendered artwork is a metaphor: one path terminates and another continues on a changed axis, making the unfulfilled expectation visible without pretending that sentences are literal plumbing.'''),
dict(index=5,slug='anastomosis',word='ANASTOMOSIS',pronunciation='uh-nas-tuh-MOH-sis',tagline='Separate routes discover a shared passage',
definition='Anastomosis is a connection between branching or tubular structures, especially blood vessels or other bodily channels, that permits communication between pathways; related scientific uses describe comparable interconnections in networks and natural forms.',
etymology='From Greek anastomosis, an opening or communication, related to anastomoun, to furnish with a mouth. The root stoma means mouth. Its anatomical history makes the image of joined openings more precise than the loose modern idea of any association.',
sections=[
dict(heading='A route with alternatives',text='Some blood vessels connect so that circulation has more than one potential route. The practical value of these connections depends on their location, caliber, pressure conditions, and disease. The existence of an anatomical connection therefore does not by itself guarantee adequate compensation when another vessel becomes blocked.'),
dict(heading='Natural and constructed joins',text='Anastomoses may occur naturally or be created surgically, as when separated sections of bowel are joined. These cases share a communication between structures, but their materials, functions, and clinical risks differ. The word identifies a relation, not a promise that the connection is functional or uncomplicated.'),
dict(heading='Beyond a simple branch',text='A branching tree divides routes without necessarily bringing them together again. An anastomosing pattern includes cross connections or reunions that change that topology. Similar descriptive language appears in botany and geomorphology, although the relevant mechanisms differ greatly between vascular tissue, fungal structures, and divided river channels.'),
dict(heading='The limits of connection',text='Interconnection can provide redundancy, but it can also redistribute pressure, spread disturbances, or create unwanted passages. Whether a network benefits from additional links depends on its purpose and dynamics. Anatomical vocabulary should not be turned into a universal political or organizational argument that more connectivity is always better.')],
literary='Where the river’s divided mouths remembered one another, the map grew veins across its own estrangements, and every elsewhere, briefly sharing blood with here, became a second chance whose pressure nobody could promise.',
art_caption='Branching vessels repeatedly reconnect, creating alternative routes while preserving the tension between separate channels and a shared circulation.',accent='CE949E',theme='201A32',
extra='''Picture two roads leaving the same town on opposite sides of a hill. If a short connecting road joins them farther along, travelers may gain an alternative route around a local obstruction. This gives an intuitive first approximation of an anastomotic connection. Yet blood does not behave like a driver selecting a preferred route. Flow depends on pressure differences and resistance, and a narrow connecting vessel may carry too little to protect tissue adequately. The road analogy clarifies topology while simplifying the dynamics that determine actual function.

In medicine, precision matters. A naturally occurring connection between arterial branches, a surgical join between bowel segments, and an abnormal communication involving vessels are not interchangeable clinical situations. Their evaluation belongs to anatomy, physiology, and the particular case. This essay describes a word and a general relation; its sculptural network cannot indicate whether any real patient has sufficient collateral circulation or whether a surgical connection is healing properly.

The tree image is particularly instructive. A strict tree has no cycles: once two branches diverge, there is no second path between them through the same network. A cross connection can create a cycle and change the set of available routes. However, not every object called an anastomosis must be interpreted as an abstract graph with exactly the same rules. Scientific terminology arises from materials and practices as well as mathematical form. A river system changes its bed; living tissue grows and remodels; a diagram holds its edges still.

This is why connection is neither an automatic virtue nor an automatic danger. The same extra route may improve resilience under one condition and transmit an unwanted disturbance under another. Explanations require the scale, substance, and direction of movement, not merely an attractive image of a web.

The literary sentence lets separated river mouths “remember” each other, turning reunion into shared circulation. Its final clause withdraws any guarantee that the alternate route will suffice. That caution is central to the image, not an ornamental afterthought. For further reading, consult an anatomical reference such as Gray’s Anatomy and a physiology text’s account of vascular resistance and collateral circulation. The locally rendered illustration is metaphorical and deliberately simplified, not an anatomical or surgical guide.'''),
dict(index=6,slug='apophenia',word='APOPHENIA',pronunciation='ap-uh-FEE-nee-uh',tagline='A pattern can outrun its evidence',
definition='Apophenia is the perception of meaningful connections or patterns where their significance is unwarranted by the evidence; it names an interpretive tendency, not proof that every surprising association is false or pathological.',
etymology='The term is associated with psychiatrist Klaus Conrad’s twentieth century account of emerging delusional experience, where German Apophänie names a revelatory sense of significance. Later usage extends beyond that clinical setting to everyday pattern attribution and mistaken connections.',
sections=[
dict(heading='Meaning arrives too quickly',text='After dreaming about a bird, you notice birds in three advertisements and infer a message addressed to you. The observations may be accurate while the interpretation exceeds what they support. Selective attention, ordinary frequency, and coincidence can generate an experience of connection without the proposed hidden cause.'),
dict(heading='Recognition needs correction',text='Pattern recognition is indispensable to learning. Its usefulness does not make every detected pattern real, nor does the possibility of error make all intuition worthless. The central question is whether a proposed connection survives comparison with alternatives, independent evidence, and occasions when the expected pattern does not appear.'),
dict(heading='A neighboring visual case',text='Pareidolia commonly names the perception of recognizable forms in ambiguous stimuli, such as a face in a cloud. It overlaps with broader discussions of apophenia but is not an exact substitute. A supposed coded message in unrelated events need not involve any face or other visual resemblance.'),
dict(heading='From hunch to hypothesis',text='A suggestive association can become a useful question if it produces testable expectations. Record the rule before looking for confirming cases, consider how many possible patterns were searched, and examine failures. These practices help separate an exploratory hunch from evidence that a proposed relationship actually holds.')],
literary='The stars, innocent of his alphabet, nevertheless spelled mother whenever he forgot the spaces, until the dark between them, drafted as punctuation, confessed a message that only his exclusions had consented to compose.',
art_caption='A scattered field becomes a compelling constellation through selected luminous connections; the unjoined points preserve the evidence the story leaves out.',accent='B3C3F0',theme='201A32',
extra='''Suppose a person inspects thousands of daily stock movements and notices that one company rises after rainy Tuesdays. The match may look remarkable if presented alone. Yet the researcher could have examined many companies, weather conditions, weekdays, and time windows. With enough possible comparisons, some attractive coincidences are expected even when no useful relation exists. The relevant question is not just how neat the selected pattern looks, but how many opportunities there were to find something equally neat.

A sensible next step is to state the rule precisely, reserve new data, and test whether the relationship persists. One should also consider plausible mechanisms and competing explanations. Successful prediction would strengthen the case for a relationship, although prediction alone might not identify its cause. Failure should count against the proposed rule rather than becoming a new sign that the hidden pattern is more elaborate than expected. Otherwise, the explanation can expand indefinitely to absorb every possible outcome.

Conrad’s clinical context deserves care. A word with a psychiatric history can acquire a wider popular use without turning ordinary coincidence noticing into a diagnosis. People routinely see shapes in clouds and remember striking coincidences. Diagnosis requires much more than the presence of an imaginative association and belongs to qualified assessment of a person’s broader circumstances. Using the term casually to dismiss another person can obscure a real argument about evidence.

There is also an asymmetry between generating and accepting ideas. A researcher or artist may deliberately try unusual associations to discover possibilities. The creative act becomes epistemically troublesome when the felt force of a connection is treated as sufficient proof. Imagination supplies candidate patterns; accountable inference asks what would distinguish a successful candidate from the many attractive failures.

In the literary sentence, the stars do not carry the interpreter’s alphabet. The message emerges from omitted spaces and selected points, dramatizing the role of exclusion in producing conviction. It is a constructed example, not a claim that astronomy or grief is intrinsically irrational. For historical orientation, consult Conrad’s Die beginnende Schizophrenie; for statistical safeguards, read an introductory treatment of multiple comparisons and out-of-sample testing. The locally rendered constellation is a metaphor, and its intentional design does not demonstrate that any corresponding pattern exists in the sky.'''),
dict(index=7,slug='autopoiesis',word='AUTOPOIESIS',pronunciation='aw-toh-poy-EE-sis',tagline='A living network remakes its conditions',
definition='Autopoiesis is the organization of a system whose processes produce components that recursively regenerate those processes and constitute the system as a distinct unity, a framework originally developed to characterize living organization.',
etymology='Coined by Humberto Maturana and Francisco Varela from Greek elements meaning self and making or production. The term emphasizes a network’s production of its own organization, rather than the simpler ideas of reproduction, independence, or making an identical copy.',
sections=[
dict(heading='The network makes itself',text='In the paradigmatic biological picture, molecular processes produce components that sustain the same network of production, including a boundary that helps constitute the cell as a unit. Components turn over while organization persists. The account concerns this circular organization rather than the endurance of a particular set of molecules.'),
dict(heading='Closure is not isolation',text='An autopoietic system exchanges matter and energy with its environment. Organizational or operational closure does not mean thermodynamic closure. The claim concerns relations among constitutive processes: their mutual dependence helps specify the system, even though continued existence depends on resources and conditions beyond its own boundary.'),
dict(heading='Reproduction is another question',text='A machine may manufacture copies of itself without meeting an autopoietic description, and an organism need not currently reproduce to remain alive. Self replication, homeostasis, and autopoiesis pick out different features. Their practical relationships must be investigated rather than collapsed into a single glamorous expression for self sufficiency.'),
dict(heading='Extensions invite dispute',text='Later theorists have applied autopoietic language to social systems and other domains. Such extensions alter the relevant components and operations and remain contested. A useful analogy does not establish that societies literally operate like cells or that one biological framework supplies a universal law governing every complex organization.')],
literary='The wall, woven by the work it sheltered, sheltered the work that rewove the wall, until inside became neither place nor prisoner but the recurring grammar by which a hunger kept becoming its own house.',
art_caption='A porous membrane and its circulating internal pathways are visibly interdependent: the boundary contains the processes that continually sustain its form.',accent='A9D3B8',theme='201A32',
extra='''Imagine a cell whose metabolic reactions continually make and replace molecules, while some of those molecules participate in the membrane that separates its interior from its surroundings. That membrane helps sustain the conditions under which the reactions continue. The production network and its boundary are not simply independent pieces assembled once and left to run. Their continued existence depends on the ongoing activity of the organized whole. This is a useful entry into the framework, although an actual biochemical account requires far more detail than the sketch supplies.

The distinction between organization and structure is crucial. Organization describes relations that must hold for the system to count as the kind of unity under discussion. Structure concerns its particular components and their actual relations at a time. A living system can undergo structural change while preserving the organization that identifies it as the same sort of system. This distinction is a theoretical tool, not a license to ignore material mechanisms or declare a system unchanged under every transformation.

A factory offers a revealing contrast. It may produce excellent bicycles while depending on workers, replacement machines, and administrative decisions that are not generated within the relevant manufacturing network. Producing an output is not automatically producing the network that produces the output. Yet the comparison depends on how a system is delimited: a careless boundary can make almost anything appear self sustaining by quietly excluding what it requires. Good applications therefore specify components, processes, and the criterion of unity.

Niklas Luhmann’s influential social theory treats communications as the operations of social systems. That proposal is not simply a laboratory result about cells translated word for word into sociology. It changes the level and subject of analysis and attracts substantive disagreement. Readers can understand the biological origin while withholding judgment about any particular social extension.

The literary sentence makes a wall both product and enabling condition of work. “Recurring grammar” names an organization that persists through activity, while hunger reminds us that the system requires external resources. Read Maturana and Varela’s Autopoiesis and Cognition: The Realization of the Living, and distinguish it from later secondary applications. The locally rendered cell is a metaphor of organizational circularity, not a biochemical model or an assertion that autopoiesis alone resolves every disputed definition of life.'''),
dict(index=8,slug='chiasmus',word='CHIASMUS',pronunciation='ky-AZ-muhs',tagline='The second crossing changes the first',
definition='Chiasmus is a crossed arrangement in which elements presented in one order recur in reverse order, often described as ABBA; the reversal may involve grammatical structures, concepts, or, in a narrower related figure, repeated words.',
etymology='From Greek chiasmos, a crossing or arrangement crosswise, related to the letter chi, written like X. The name makes a visible figure of reversed correspondence, although actual examples may operate through syntax or meaning rather than literal intersecting lines.',
sections=[
dict(heading='Order becomes an argument',text='A phrase can place persons before institutions, then institutions before persons, making the reversal itself carry a claim about responsibility. The pattern supplies balance and memorability. It does not prove the relationship it asserts, because a symmetrical sentence can arrange weak reasoning as elegantly as strong reasoning.'),
dict(heading='A neighboring exact reversal',text='Antimetabole usually names the repetition of the same words in reversed order, while chiasmus can involve a broader reversal of grammatical or conceptual relations. Terminology varies among rhetorical traditions. Stating which elements cross is more useful than policing every historical example into a perfectly rigid taxonomy.'),
dict(heading='Scale changes the evidence',text='Chiasmus can appear within a short phrase or be proposed as an organizing pattern across a much longer passage. Larger claims require stronger evidence about boundaries and correspondences. Selective grouping can manufacture apparent symmetry, especially when intervening material or inconvenient differences are quietly removed from the analysis.'),
dict(heading='Return without sameness',text='The second occurrence of an element arrives after its counterpart has changed the context. Reversal can therefore create development rather than mere repetition: what began as an agent returns as an object, or what appeared subordinate becomes governing. The crossing can question hierarchy as easily as reinforce it.')],
literary='She made a home of the language that had made a stranger of her, and the stranger, learning to house what had unhoused her, found every returning word crossing the threshold in another person’s shoes.',
art_caption='Two luminous strands exchange positions at repeated crossings, turning balanced form into an image of relations transformed by reversal.',accent='E4A09D',theme='201A32',
extra='''Consider the invented sentence “We shape the paths that later shape us.” It repeats the verb while reversing the relation between human agents and the routes they create. The practical claim is that built environments influence future behavior. The crossed structure compresses reciprocal causation into a memorable shape. To decide whether the claim is true in a particular case, however, one still needs evidence about the environment and the people who use it. Rhetorical fit and empirical fit are different achievements.

For a deliberately simple structural example, take “I admire her courage; her patience I respect.” The first clause places subject and verb before object; the second fronts an object before its subject and verb. The correspondence is grammatical rather than a perfect repetition of identical words. A classic antimetabole instead reverses lexical items themselves. These distinctions help describe the machinery of a passage, although handbooks and scholars do not always use the labels in exactly the same way.

There is a temptation to discover vast crossed structures in any sufficiently rich work. An analyst can choose broad themes for the outer units, narrow themes for the inner units, omit awkward passages, and thereby produce an attractive diagram. A persuasive account should explain why its units belong where they do, demonstrate comparable levels of specificity, and consider alternative arrangements. The more flexible the matching rule becomes, the less surprising the resulting symmetry is. Close reading benefits from formal imagination disciplined by textual resistance.

The original dense sentence works through a series of crossings: language makes a stranger, the stranger makes a home, and the home must accommodate what once excluded its inhabitant. The sequence is an extended meditation on reversal rather than a perfectly exhaustive four-term diagram. It includes echoes that exceed a strict ABBA pattern. Naming those limits is more instructive than declaring every attractive recurrence an exact chiasmus.

For further reading, consult Richard A. Lanham’s A Handlist of Rhetorical Terms and compare close readings that explicitly identify the linguistic units they treat as corresponding. The locally rendered paired strands offer a metaphor of crossing and reciprocal transformation. Their physical symmetry does not imply that a well made rhetorical sentence is logically valid, politically fair, or historically accurate; those judgments require arguments beyond its formal grace.''')
]

def wc(s):return len(s.split())
for e in ENTRIES:
    extra=e.pop('extra')
    stem=f"{e['index']:02d}-{e['slug']}"
    (OUT/(stem+'.json')).write_text(json.dumps(e,ensure_ascii=False,indent=2)+'\n')
    md=f"# {e['word'].title()}\n\n*{e['pronunciation']} · {e['tagline']}*\n\n{e['definition']}\n\n{e['etymology']}\n\n"
    for s in e['sections']:md+=f"## {s['heading']}\n\n{s['text']}\n\n"
    md+=f"## An original literary sentence\n\n> {e['literary']}\n\n## Working through the word\n\n{extra}\n"
    (NOTES/(stem+'.md')).write_text(md)
    print(stem,'essay',wc(md),'definition',wc(e['definition']),'etymology',wc(e['etymology']),'sections',[wc(s['text']) for s in e['sections']],'literary',wc(e['literary']))
